// Generated by scripts/import-wp.mjs — do not edit.
import p0 from "./pages/index.json";
import p1 from "./pages/blog.json";
import p2 from "./pages/newsletter.json";
import p3 from "./pages/politica-de-cookies.json";
import p4 from "./pages/declaracion-de-privacidad.json";
import p5 from "./pages/reserva-mesa.json";
import p6 from "./pages/comida-norte-sur-centro-vietnam.json";
import p7 from "./pages/donde-se-come-mejor-en-vietnam.json";
import p8 from "./pages/lugares-visitar-en-vietnam.json";
import p9 from "./pages/cultura-culinaria-de-vietnam.json";
import p10 from "./pages/que-es-pho.json";
import p11 from "./pages/cafe-de-filtro-vietnamita.json";
import p12 from "./pages/la-comida-callejera-de-vietnam.json";
import p13 from "./pages/gastronomia-vietnamita.json";
import p14 from "./pages/platos-vietnamitas.json";
import p15 from "./pages/en.json";
import notFound from "./pages/_404.json";

export const pages = {
  "/": p0,
  "/blog/": p1,
  "/newsletter/": p2,
  "/politica-de-cookies/": p3,
  "/declaracion-de-privacidad/": p4,
  "/reserva-mesa/": p5,
  "/comida-norte-sur-centro-vietnam/": p6,
  "/donde-se-come-mejor-en-vietnam/": p7,
  "/lugares-visitar-en-vietnam/": p8,
  "/cultura-culinaria-de-vietnam/": p9,
  "/que-es-pho/": p10,
  "/cafe-de-filtro-vietnamita/": p11,
  "/la-comida-callejera-de-vietnam/": p12,
  "/gastronomia-vietnamita/": p13,
  "/platos-vietnamitas/": p14,
  "/en/": p15,
};

export { notFound };
